### ISSUE TITLE
`LuxTestUtils.Constant` clashes with `DifferentiationInterface.Constant`

### ISSUE THREAD

**Issue by gdalle** [LuxDL/Lux.jl#1103]
I realized this in https://github.com/JuliaDiff/DifferentiationInterface.jl/pull/636, where the DI tests fail because the name clash (caused by #1042) now makes `Constant` undefined. Of course it's on me because I didn't use explicit imports, but still a cautionary tale: whenever people do `using LuxTestUtils; using DifferentiationInterface` in the same REPL, they cannot use `Constant`. Maybe you could actually use the `Constant` type from DI in LuxTestUtils? It doesn't seem to be public anyway.

**Comment by avik-pal** [comment]
I would say the solution would be to use explicit imports. Also I don't foresee end-users doing `using LuxTestUtils` since it is mostly supposed to be used for testing and I don't think users really know about it

**Comment by gdalle** [comment]
Yeah I ended up doing the right thing and putting explicit imports everywhere.

But regardless of that, it seems a bit weird on your end to export undocumented Symbols?

**Comment by avik-pal** [comment]
> But regardless of that, it seems a bit weird on your end to export undocumented Symbols?

LuxTestUtils is mostly undocumented since it is meant to be an internal package. I am not against adding docs for it, but it is really low on my priority. With the new sources functionality, it is now possible to install unregistered packages but that was not a thing before 1.11, and hence it was registered while being mostly for internal usage.
