### ISSUE TITLE
Bug when converting model with single layer to SimpleChains

### ISSUE THREAD

**Issue by gzagatti** [LuxDL/Lux.jl#545]
I have tried to convert the following model to SimpleChains:

```julia
import SimpleChains: static

model = Dense(10 => 5)
adaptor = ToSimpleChainsAdaptor((static(10),))
simple_chains_model = adaptor(model)
```

But it fails with:

```
ERROR: MethodError: no method matching __fix_input_dims_simplechain(::SimpleChains.Conv{…}, ::Tuple{…})

Closest candidates are:
  __fix_input_dims_simplechain(::Vector, ::Any)
   @ LuxSimpleChainsExt ~/.julia/packages/Lux/ufsdt/ext/LuxSimpleChainsExt.jl:9
...
```

I believe this is because `Dense(10 => 5)` is not a chain. I have also tried to use `model = Chain(Dense(10 => 5),)` but it raises the same error as well.

On the other hand, the following does not raise any errors:

```julia
model = Chain(Dense(10 => 5), Dense(1 => 1))
adaptor = ToSimpleChainsAdaptor((static(10),))
simple_chains_model = adaptor(model)
```

Maybe I am using `ToSimpleChainsAdaptor` incorrectly. I am new to `Lux` and `SimpleChains`.

**Comment by avik-pal** [comment]
No, your use is correct; it is just that SimpleChains expects a chain of layers which I had mimicked and expected the entry point to be a `Chain` (`model = Chain(Dense(10 => 5),)` outputs a `Dense(10 => 5)`). 

Once #547 is merged, this case should be handled, but a warning will still be printed because we are making an automatic conversion, which has the potential to fail.
