### ISSUE TITLE
The returned values loss and train_state of single_train_step! are not compatible

### ISSUE THREAD

**Issue by wg030** [LuxDL/Lux.jl#979]
I noticed that when you call `single_train_step!` like for example as given in the quickstart tutorial

`_, loss, _, train_state = Training.single_train_step!(AutoZygote(), MSELoss(), (x, dev(rand(rng, Float32, 10, 2))), train_state)`

the resulting `loss` does not refer to the new resulting `train_state` but rather to the old `train_state` you had before carrying out the single train step.

This probably does not matter too much in practice and can easily be handled, but wouldn't you intutively expect `loss` and `train_state` to be compatible when they are the returned values of `single_train_step!`??? Personally I would.

**Comment by avik-pal** [comment]
So the loss currently being returned is the one from `compute_gradients` (https://lux.csail.mit.edu/stable/api/Lux/utilities#Lux.Training.compute_gradients), i.e., the loss corresponding to which the gradient was computed.

> This probably does not matter too much in practice and can easily be handled

Note that computing this essentially runs another network forward pass in test mode. While it seems easy (and it technically is), it effectively doubles the number of function calls over training.

I will mark this as not going to fix since users can run inference if they need to, and it doesn't make sense to slow down training for everyone else.
